-- ALTER TABLE playlist_song
-- -- ADD INDEX PLAYLIST_ID_FK (`PLAYLIST_ID` ASC);
--
-- ADD CONSTRAINT PLAYLIST_ID_FK
--   FOREIGN KEY (PLAYLIST_ID) REFERENCES playlists (ID)
--   ON DELETE RESTRICT
--   ON UPDATE RESTRICT;


CREATE TABLE playlist_song
(
    ID              VARCHAR(255) not null PRIMARY KEY,
    SONG_ID         VARCHAR(100) not null,
    PLAYLIST_ID     VARCHAR(100) not null,
    CONSTRAINT PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES playlists (ID),
    CONSTRAINT SONG_ID_FK FOREIGN KEY (SONG_ID) REFERENCES songs (ID)
);

ALTER TABLE playlists
    ADD CONSTRAINT PLAYLIST_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES users (ID)
